function track polish

diff --git a/cloud-functions-http/deploying-functions/check-shell b/cloud-functions-http/deploying-functions/check-shell
--- a/cloud-functions-http/deploying-functions/check-shell
+++ b/cloud-functions-http/deploying-functions/check-shell
@@ -15,6 +15,12 @@ if [ -f /home/main.py ]; then
   RUNTIME=python37
 fi
 
+gcloud functions describe $FUNCTION
+if [ $? -ne 0 ]; then
+    fail-message "Could not find a function that triggers on HTTP requests. Type 'hint' if you are stuck."
+    exit 1
+fi
+
 gcloud functions describe $FUNCTION --format=json | jq -e '.entryPoint != null and .runtime != null and .httpsTrigger.url != null'
 if [ $? -ne 0 ]; then
     fail-message "Could not find a function that triggers on HTTP requests. Type 'hint' if you are stuck."
