Add translation scripts and translates Cloud ML APIs (#5)

diff --git a/cloud-ml-apis/recognizing-audio/check-shell b/cloud-ml-apis/recognizing-audio/check-shell
--- a/cloud-ml-apis/recognizing-audio/check-shell
+++ b/cloud-ml-apis/recognizing-audio/check-shell
@@ -13,14 +13,16 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
+source /root/.translationsenv
+
 if [ ! -f /usr/local/bin/answer.txt ]; then
-    fail-message "You haven't answered yet! You must run the \"answer\" command and press ENTER"
+	fail-message "$FAIL_MESSAGE_NO_ANSWER"
+	exit 1
 fi
 
 ANSWER=$(cat /usr/local/bin/answer.txt)
 
-CORRECT="jurassic park"
-if [[ "$CORRECT" != "$ANSWER" ]]; then
-    fail-message "Your answer is incorrect! Type \"hint\" if you are stuck."
+if [[ "$RECOGNIZING_AUDIO_ANSWER" != "$ANSWER" ]]; then
+    fail-message "$FAIL_MESSAGE_INCORRECT"
     exit 1
 fi
