Update gke track

diff --git a/gke-microservices/01-create-a-namespace/check-shell b/gke-microservices/01-create-a-namespace/check-shell
--- a/gke-microservices/01-create-a-namespace/check-shell
+++ b/gke-microservices/01-create-a-namespace/check-shell
@@ -12,34 +12,8 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-kubectl label namespace default time=$(date '+%s') --overwrite # mark cluster as still used
-
-echo "$DEPLOYMENT_HELP" > /root/.instruqt/help.txt
-
-echo "$DEPLOYMENT_HINT" > /root/.instruqt/hint.txt
-
-set-workdir /home
-
-cat <<EOF > /home/deployment.yaml
-apiVersion: apps/v1
-kind: Deployment
-metadata:
-  namespace: <?>
-  name: <?>
-spec:
-  replicas: <?>
-  selector:
-    matchLabels:
-      <?>: <?>
-  template:
-    metadata:
-      labels:
-        <?>: <?>
-    spec:
-      containers:
-      - image: <?>
-        name: app
-        ports:
-          - name: http
-            containerPort: 3000
-EOF
+kubectl get ns challenge
+if [ $? -ne 0 ]; then
+    fail-message "Could not find a namespace called 'challenge'. Type 'hint' if you are stuck."
+    exit 1
+fi
diff --git a/gke-microservices/03-service/check-shell b/gke-microservices/03-service/check-shell
--- a/gke-microservices/03-service/check-shell
+++ b/gke-microservices/03-service/check-shell
@@ -12,8 +12,15 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-kubectl get ns challenge
+kubectl get service frontend-service -n challenge
 if [ $? -ne 0 ]; then
-    fail-message "$NAMESPACE_FAIL"
+    fail-message "Could not find Service called 'frontend-service' in the namespace 'challenge'. Type 'hint' if you are stuck."
+    exit 1
+fi
+
+
+kubectl get service frontend-service -n challenge -o json | jq -e '.spec.selector != null and .spec.selector.role != null and .spec.selector.role == "frontend" and .spec.type == "LoadBalancer"'
+if [ $? -ne 0 ]; then
+    fail-message "Service is not configured correctly. Type 'hint' if you are stuck."
     exit 1
 fi
