moved GKE track to use new base image and helper scripts

diff --git a/gke-microservices/configmaps-secrets/check-shell b/gke-microservices/configmaps-secrets/check-shell
--- a/gke-microservices/configmaps-secrets/check-shell
+++ b/gke-microservices/configmaps-secrets/check-shell
@@ -1,12 +1,25 @@
 #!/bin/bash
-kubectl get configmap app -o json | jq -e '.data.username != null'
+
+kubectl get configmap app -o json --namespace challenge
 if [ $? -ne 0 ]; then
-    fail-message "Could not find ConfigMap called 'app' with a key called 'username' in the namespace `challenge`"
+    fail-message "Could not find ConfigMap called 'app' in the namespace 'challenge'. Type 'hint' if you are stuck."
     exit 1
 fi
 
-kubectl get secret app -o json | jq -e '.data.password != null'
+kubectl get configmap app -o json --namespace challenge | jq -e '.data.username != null'
 if [ $? -ne 0 ]; then
-    fail-message "Could not find Secret called 'app' with a key called 'password' in the namespace `challenge`"
+    fail-message "Could not find ConfigMap called 'app' with a key called 'username' in the namespace 'challenge'. Type 'hint' if you are stuck."
+    exit 1
+fi
+
+kubectl get secret app -o json --namespace challenge
+if [ $? -ne 0 ]; then
+    fail-message "Could not find Secret called 'app' in the namespace 'challenge'. Type 'hint' if you are stuck."
+    exit 1
+fi
+
+kubectl get secret app -o json --namespace challenge | jq -e '.data.password != null'
+if [ $? -ne 0 ]; then
+    fail-message "Could not find Secret called 'app' with a key called 'password' in the namespace 'challenge'. Type 'hint' if you are stuck."
     exit 1
 fi
